### ISSUE TITLE
No health or mana mp3 files

### ISSUE THREAD

**Issue by labrys** [labrys/fritzlsound#1]
@fritzl123321

I've updated the code with some style changes and some optimizations.  If you could post a copy of the health.mp3 and mana.mp3 files I will add them to the project.

**Comment by fritzl123321** [comment]
> @fritzl123321
> 
> I've updated the code with some style changes and some optimizations. If you could post a copy of the health.mp3 and mana.mp3 files I will add them to the project.



[health and mana.zip](https://github.com/labrys/fritzlsound/files/3099217/health.and.mana.zip)

**Comment by labrys** [comment]
Ok those files have been added.   If you could also post some screenshots of the screens you are trying to capture I can do some tests to see if they work properly.  A health normal, health regular, mana regular, and mana low at each of the 4 mana states would be ideal, but a single screenshot would be good enough.

**Comment by labrys** [comment]
If you prefer you can email me the screenshots `labrys.git@gmail.com`

**Comment by labrys** [comment]
Added

**Comment by fritzl123321** [comment]
> Added

Thank you very much, I will try it as an exe file! I have a question about the code because I also want to improve from my mistakes: 

log = logging.getLogger(__name__)

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    main()

what do these 2 lines do? Will I need those lines a lot?

**Comment by fritzl123321** [comment]
> Added

Okay, so as an exe it still doesn't work, showing a pop up that says failed to execute script 'Name'.

**Comment by labrys** [comment]
The logging uses a logger instead of print to output.  Logging is usually more efficient than print statements.

The `if __name__ == '__main__':` only runs the script if you run it directly but allows you to also import the python file as a module for use in other scripts.  The main reason to do this for a script like this is to set up unit tests to test the functionality.

**Comment by labrys** [comment]
I haven't pushed my tests yet, but it shows that the Health function does not work, the Q and R tests do work, and W and E do not.

**Comment by labrys** [comment]
Question about functionality, I assume you only want to alert on mana if one of Q W E or R is OOM.  As it currently exists it will warn for all of the ones that are OOM, so up to 4 times for a single check.
